site_name: Lorekeeper Docs
site_url: 'https://lk-arpg.github.io/lk-docs/'
repo_url: https://github.com/lk-arpg/lorekeeper
repo_name: lk-arpg/lorekeeper

nav:
  - Home: 'index.md'

  - v3.0 Update:
    - Release Notes: 'release-notes.md'
    - Upgrade Guide: 'guides/upgrade.md'

  - Getting Started:
    - Setting Up: 'guides/setup-index.md'
    - Configuring Lorekeeper: 'guides/configuring.md'
    - Updating Lorekeeper: 'guides/update.md'
    - Social Media Authentication:
      - Discord: 'guides/socmed/discord.md'
      - deviantArt: 'guides/socmed/deviantart.md'
      - Imgur: 'guides/socmed/imgur.md'
      - Instagram: 'guides/socmed/instagram.md'
      - Toyhou.se: 'guides/socmed/toyhouse.md'
      - Tumblr: 'guides/socmed/tumblr.md'
      - Twitch: 'guides/socmed/twitch.md'
      - Twitter: 'guides/socmed/twitter.md'
  
  - Features:
    - Admin Panel: 'features/admin-panel.md'
    
    - Characters: 'features/characters.md'
    - MYO Slots: 'features/myo-slots.md'
    - Character Images: 'features/character-images.md'
    - Design Updates: 'features/design-updates.md'
    - Masterlist: 'features/masterlist.md'
    - Bookmarks: 'features/bookmarks.md'

    - Species: 'features/species.md'
    - Rarities: 'features/rarities.md'
    - Traits: 'features/traits.md'

    - Currencies: 'features/currencies.md'
    - Items: 'features/items.md'
    - Shops: 'features/shops.md'
    - Trades: 'features/trades.md'
    - Loot Tables: 'features/loot-tables.md'

    - Galleries: 'features/galleries.md'

    - Prompts: 'features/prompts.md'
    - Claims: 'features/claims.md'

    - News: 'features/news.md'
    - Sales: 'features/sales.md'

    - Raffles: 'features/raffles.md'

    - User Accounts: 'features/user-accounts.md'
    - User Ranks: 'features/user-ranks.md'
    - Notifications: 'features/notifications.md'
    - Invitation Keys: 'features/invitation-keys.md'

    - Reports: 'features/reports.md'
    
    - Config Files: 'features/config-files.md'
    - Site Settings: 'features/site-settings.md'
    - Site Pages: 'features/site-pages.md'
    - Site Images: 'features/site-images.md'
    - File Manager: 'features/file-manager.md'

  - Design:
    - How Random is Random?: 'features/randomness.md'

  - Development:
    - Contributing: 'contributing.md'
    - Tutorial - Creating Item Types: 'guides/creating-item-types.md'
    
  - Version History:
    - v1.0.x: 'version-history/v1.0.md'
    - v1.1.x: 'version-history/v1.1.md'
    - v1.2.x: 'version-history/v1.2.md'
    - v1.3.x: 'version-history/v1.3.md'
    - v1.4.x: 'version-history/v1.4.md'
    - v1.5.x: 'version-history/v1.5.md'
    - v1.6.x: 'version-history/v1.6.md'
    - v1.7.x: 'version-history/v1.7.md'
    - v2.0.x: 'version-history/v2.0.md'
    - v2.1.x: 'version-history/v2.1.md'
    - v3.0.0 Pre-release: 'version-history/v3.0.pre.md'
    - v3.0.x: 'version-history/v3.0.md'

theme:
  name: 'material'
  language: 'en'
  features:
    - navigation.instant
  
  favicon: images/favicon.ico
  
  icon:
    repo: fontawesome/brands/github

  palette:
  - media: '(prefers-color-scheme)'
    toggle:
      icon: material/brightness-auto
      name: System preference
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: deep purple
    accent: cyan
    toggle:
      icon: material/weather-night
      name: Light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: deep purple
    accent: cyan
    toggle:
      icon: material/weather-sunny
      name: Dark mode

extra:
  version:
    provider: mike
    default: latest
    alias: true

markdown_extensions:
  - admonition
  - sane_lists
  - toc:
      permalink: true
  - extra
  - footnotes
  - codehilite:
      guess_lang: false
  - attr_list
  - md_in_html

  - pymdownx.blocks.caption
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets
  